trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: LetsEncryptGoDaddy

steps:
- script: |
    echo "---------------------"
    printenv | sort
    ls -la
    pwd
    echo "---------------------"
    # Run bash script
    chmod +x ./create-certificate-godaddy.sh
    ./create-certificate-godaddy.sh
    echo "---------------------"
    echo "Script debug log file"
    echo "---------------------"
    cat ./letsencrypt/logs/letsencrypt.log
    echo "---------------------"
  env:
    # Map the pipeline variable to the script environment variable
    clientId: $(sp-clientId)
    clientSecret: $(sp-clientSecret)
    tenantId: $(sp-tenantId)
    subscriptionID: $(sp-subscriptionId)
    domainName: $(domain)
    emailAddress: $(emailAddress)
    keyVaultName: $(keyVaultName)
    resourceGroups: $(resource-group)
    GoDaddyAPIKey: $(GoDaddyAPIKey)
    GoDaddyAPISecret: $(GoDaddyAPISecret)
  displayName: 'Lets Encrypt Certbot Certificates Creation'
